routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

  

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/', function () {
        return redirect('home');

   });
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/contact', function () {
    return view('contact');
});

Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');

Route::get('/homelist', 'FileController@homelist')->name('homelist');



Route::get('profile', 'UserController@profile');

Route::post('profile', 'UserController@update_avatar');

Route::post('signature', 'UserController@update_signature')->name('signature');

Route::post('contact', 'ContactController@store')->name('contact');

Route::get('verify-user/{code}','Auth\RegisterController@activateUser')->name('activate.user');



//Admin routes


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
     
    Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'store']]);

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
     
    Route::resource('/registration', 'registrationController', ['except' => ['show', 'create', 'store']]);

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
     
    Route::resource('/group', 'groupController');

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
     
    Route::resource('/groupUser', 'groupUserController', ['except' => ['show']]);

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
     
    Route::resource('/announcement', 'announcementController', ['except' => ['show']]);

});


Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
     
    Route::resource('/notification', 'notificationController');

});





Route::get('/activation', 'HomeController@index')->name('activation');


Route::post('file/upload', 'FileController@upload')->name('file.upload');



Route::post('/upload', 'FileController@upload')->name('upload');

Route::get('push', 'FileController@push')->name('push');


Route::get('/docs/{filename}', 'FileController@getFile');


// Route::get('file','FileController@create');
// Route::post('file','FileController@store');




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


Route::get('video/{file}', 'FileController@video')->name('video');
Route::get('audio/{file}', 'FileController@audio')->name('audio');
Route::get('image/{file}', 'FileController@image')->name('image');
Route::get('text/{file}', 'FileController@text')->name('text');
Route::get('sheet/{file}', 'FileController@sheet')->name('sheet');
Route::get('pdf/{file}', 'FileController@pdf')->name('pdf');
Route::get('slide/{file}', 'FileController@slide')->name('slide');




// folders

Route::get('folder.index', 'FolderController@index')->name('folder.index');

Route::get('folder.create', 'FolderController@createfolder')->name('folder.create');

Route::post('create', 'FolderController@store')->name('create');

//folder files

Route::get('subhome/{folder}', 'FolderfilesController@files')->name('subhome');

Route::post('subfile/upload', 'FolderfilesController@store')->name('subfile.upload');



// Sub folders

Route::get('subFolderLoad/{folder}', 'SubfolderController@subFolderLoad')->name('subFolderLoad');

Route::get('subfolder.create', 'SubfolderController@createfolder')->name('subfolder.create');

Route::post('subfolderCreate', 'SubfolderController@store')->name('subfolderCreate');





Route::get('subvideo/{file}', 'SubfolderController@subvideo')->name('subvideo');
Route::get('subaudio/{file}', 'SubfolderController@subaudio')->name('subaudio');
Route::get('subimage/{file}', 'SubfolderController@subimage')->name('subimage');
Route::get('subtext/{file}', 'SubfolderController@subtext')->name('subtext');
Route::get('subsheet/{file}', 'SubfolderController@subsheet')->name('subsheet');
Route::get('subpdf/{file}', 'SubfolderController@subpdf')->name('subpdf');
Route::get('subslide/{file}', 'SubfolderController@subslide')->name('subslide');




// Return route 
Route::get('back', 'SubfolderController@back')->name('back');

//sharessssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

Route::get('share/{file}', 'ShareController@share')->name('share');


Route::get('subshare/{file}', 'ShareController@subshare')->name('subshare');

Route::get('rrrrrr/{file}', 'ShareController@subshare')->name('rrrrrr');

Route::post('shareFile', 'ShareController@store')->name('shareFile');











// Notifications
Route::get('notificationindex', 'SubfolderController@back')->name('back');





Route::get('notificationview/{announcement}', 'Admin\notificationController@notificationview')->name('notificationview');
Route::post('notificationDelete/{notification}', 'Admin\notificationController@notificationDelete')->name('notificationDelete');

Route::get('filenotificationview/{filenotification}', 'FileNotificationController@filenotificationview')->name('filenotificationview');
Route::post('filenotificationview/{filenotification}', 'FileNotificationController@filenotificationDelete')->name('filenotificationDelete');











// DELETE 

Route::get('deleteFile/{file}', 'FileController@deleteFile')->name('deleteFile');

Route::get('deleteSubFile/{file}', 'SubfolderController@deleteSubFile')->name('deleteSubFile');





// FOLDER DELETE ?

Route::get('deleteFolder/{folder}', 'FolderController@deleteFolder')->name('deleteFolder');

Route::get('deleteSUbFolder/{folder}', 'SubfolderController@deleteSUbFolder')->name('deleteSUbFolder');






Route::get('inbox', 'ContactController@index')->name('inbox');


Route::get('inboxView/{contact}', 'ContactController@inboxView')->name('inboxView');
Route::Post('inboxDelete/{contact}', 'ContactController@destroy')->name('inboxDelete');

Route::post('inboxTreated/{contact}', 'ContactController@inboxTreated')->name('inboxTreated');
Route::post('inboxProgress/{contact}', 'ContactController@inboxProgress')->name('inboxProgress');
Route::post('inboxNotTreated/{contact}', 'ContactController@inboxNotTreated')->name('inboxNotTreated');













// Route::get('search','HomeController@result');
Route::get('/live_search/action', 'HomeController@action')->name('live_search.action');



//quota
Route::get('quota', 'QuotaController@index')->name('quota');



// comments

Route::get('comment.index', 'CommentController@index')->name('comment.index');

Route::post('comment.create', 'CommentController@store')->name('comment.create');

Route::get('comment.closeComment/{comment}', 'CommentController@closeComment')->name('comment.closeComment');


Route::get('comment.printComment/{file}', 'CommentController@printComment')->name('comment.printComment');


// Replies

Route::get('reply.index', 'ReplyController@index')->name('reply.index');

Route::post('reply.create', 'ReplyController@store')->name('reply.create');

Route::get('reply.closeReply/{reply}', 'ReplyController@closeReply')->name('reply.closeReply');


//Request signature
Route::post('requestSignature', 'FileNotificationController@requestSignature')->name('requestSignature');
Route::post('requestStamp', 'FileNotificationController@requestStamp')->name('requestStamp');
Route::post('requestSignatureStamp', 'FileNotificationController@requestSignatureStamp')->name('requestSignatureStamp');

Route::post('requestSheetSignatureStamp', 'FileNotificationController@requestSheetSignatureStamp')->name('requestSheetSignatureStamp');

Route::post('requestAuthImage', 'FileNotificationController@requestAuthImage')->name('requestAuthImage');


// Sign and stamp docs

Route::get('sign/{file}', 'SignStampController@sign')->name('sign');
Route::get('stamp/{file}', 'SignStampController@stamp')->name('stamp');
Route::get('signstamp/{file}', 'SignStampController@signstamp')->name('signstamp');

Route::post('confirmSS', 'SignStampController@store')->name('confirmSS');
Route::get('downloadSigned/{id}', 'SignStampController@downloadSigned')->name('downloadSigned');
Route::get('downloadStamped/{id}', 'SignStampController@downloadStamped')->name('downloadStamped');
Route::get('downloadsignstamp/{id}', 'SignStampController@downloadsignstamp')->name('downloadsignstamp');

// Sign and stamp sheets

Route::get('signSheet/{file}', 'SignStampController@signSheet')->name('signSheet');
Route::get('stampSheet/{file}', 'SignStampController@stampSheet')->name('stampSheet');
Route::get('signstampSheet/{file}', 'SignStampController@signstampSheet')->name('signstampSheet');

Route::get('authImage/{file}', 'SignStampController@authImage')->name('authImage');


// Download signed file
Route::get('downloadSignedSheet/{id}', 'SignStampController@downloadSignedSheet')->name('downloadSignedSheet');

app/Announcement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    protected $fillable = [
        'tittle','sender', 'message', 
    ];
}

app/Http/Controllers/Admin/announcementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Announcement;
use Gate;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
Use Alert;


class announcementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $announcements =Announcement::all();  
        return view('admin.announcement.index')-> with('announcements', $announcements);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.announcement.createannouncement');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'tittle' => 'required|min:5',
            'sender' => 'required|min:5',
            'message' => 'required|min:10'
        ]);

        Announcement::create($request->only(['tittle', 'sender', 'message']));

        return redirect()->route('admin.announcement.index')->with('toast_success', 'Announcement created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function edit(Announcement $announcement)
    {
        if (Gate:: denies('edit-users')){
            return redirect(route('admin.announcement.index'));
        }
      

       return view('admin.announcement.edit')->with ([
           'announcement' => $announcement,
       ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Announcement $announcement)
    {
        //
        $request->validate([
            'tittle' => 'required|min:5',
            'sender' => 'required|min:5',
            'message' => 'required|min:10'
            ]);
    
            $announcement->update($request->all());
    
            return redirect()->route('admin.announcement.index')->with('toast_success','Announcement updated successfully');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Announcement  $announcement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Announcement $announcement)
    {
        $announcement->delete();
        return redirect()->route('admin.announcement.index')->with('toast_success', 'Announcement successfully removed.');
    }
}

resources/views/admin/announcement/createannouncement.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-4">
              
            <div class="card-header bg-light text-dark font-weight-bold"> New Announcement
                <div class="float-right">
                    <a href="{{ route('admin.announcement.index') }}" class="btn btn-outline-light text-danger btn-sm"> <i class="fa fa-times" aria-hidden="true"></i> Cancel</a>
                </div>  
            </div>

                <div class="card-body">

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <p>
                            <strong>Input Error!</strong>
                        </p>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
               
                   
               
                    <form action="{{route('admin.announcement.store')}}" method="POST">
                        {{ csrf_field() }}

                        {{ method_field('POST') }}
                        

                        <div class="form-group">
                            <input type="text" class="form-control" id="tittle" name="tittle" value="{{ old('tittle') }}" placeholder="Tittle">
                        </div>

                        <div class="form-group">
                                <input type="text" class="form-control" id="sender" name="sender" value="{{ old('sender') }}" placeholder="From">
                            </div>
                 
                         <div class="form-group">
                            <label for="message">Message Body </label>
                            <textarea class="form-control" id="message" name="message" rows="5">{{ old('message') }}</textarea>
                        </div>
                 
                        <button type="submit" class="btn btn-primary float-right"><i class="fa fa-plus" aria-hidden="true"> </i> Create</button>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

@endsection

resources/views/admin/announcement/edit.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-4">
              
            <div class="card-header bg-success text-white "> Edit Announcement:
                <div class="float-right">
                    <a href="{{ route('admin.announcement.index') }}" class="btn btn-outline-light btn-sm"> <i class="fa fa-times" aria-hidden="true"></i> </a>
                </div>  
            </div>

                <div class="card-body">

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <p>
                            <strong>Input Error!</strong>
                        </p>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
               
                   
               
                    <form action="{{route('admin.announcement.update',$announcement->id)}}" method="post">
                        {{ csrf_field() }}

                        {{ method_field('PUT') }}
                        

                        <div class="form-group">
                            <input type="text" class="form-control" id="tittle" name="tittle" value="{{ $announcement->tittle }}">
                        </div>

                        <div class="form-group">
                                <input type="text" class="form-control" id="sender" name="sender" value="{{ $announcement->sender }}">
                            </div>
                 
                         <div class="form-group">
                            <label for="message">Message Body </label>
                            <textarea class="form-control" id="message" name="message" rows="5">{{ $announcement->message }}</textarea>
                        </div>
                 
                        <button type="submit" class="btn btn-success float-right"><i class="fa fa-plus" aria-hidden="true"> </i> Update</button>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

@endsection

resources/views/admin/announcement/index.blade.php
@extends('layouts.app')

@section('content')





<div class="container-fluid">
    <div class="row justify-content-center m-0">
        <div class="col-sm-2 p-0">
        
             <!-- Sidebar -->
             <div class="bg-light border" id="sidebar-wrapper">
                  
                <div class="list-group list-group-flush">
                  <a href="#" class="list-group-item list-group-item-action bg-dark text-white">ADMIN</a>
                <a href="{{ route('admin.users.index') }}" class="list-group-item list-group-item-action bg-light font-weight-bold">USERS</a>
                  {{-- <a href="{{ route('admin.group.index') }}" class="list-group-item list-group-item-action bg-light font-weight-bold">GROUPS</a> --}}
                  <a href="{{ route('admin.announcement.index') }}" class="list-group-item list-group-item-action bg-success text-white font-weight-bold">ANNOUNCEMENT</a>
                  <a href="{{ route('admin.registration.index') }}" class="list-group-item list-group-item-action bg-light font-weight-bold">REGISTRATION</a>
                  <a href="{{ route('inbox') }}" class="list-group-item list-group-item-action bg-light font-weight-bold">INBOX
                    @php
                      $count = DB::table('contacts')->where('status','=','Not Treated')->count();
                    @endphp
                    @if ($count !== 0)
                      <span class="badge badge-pill badge-danger ml-3">
                        {{ $count }}
                      </span>
                    @endif
                  </a>
                  <a href="{{ route('quota') }}" class="list-group-item list-group-item-action bg-light font-weight-bold">QUOTA</a>
                 
                </div>
              </div>
              <!-- /#sidebar-wrapper -->


        </div>

       

        <div class="col-md-10">
            <div class="row mb-0">
           {{-- breadcrumb --}}

                  <nav aria-label="breadcrumb col-sm-5">
                      <ol class="breadcrumb ">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a></li>
                        <li class="breadcrumb-item"><a href="#">Configuration</a></li>
                        <li class="breadcrumb-item "><a href="#">Admin</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Announcements</li>
                      </ol>
                    </nav>
                    <div class="col-sm-3"> 
                        {{-- <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-default bg-light dropdown-toggle  p-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-cog    "></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                              <a class="dropdown-item" href="#">Dropdown link</a>
                              <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                          </div> --}}

                          <div class="btn-group" role="group" aria-label="Third group">
                              <button type="button" class="btn btn-default bg-light p-2"><i class="fa fa-refresh" aria-hidden="true"></i></button>
                            </div>
                    </div>

            </div>

            <div class="card mt-3">

             

                <div class="card-header bg-light text-dark font-weight-bolder"><h3 class="font-weight-bolder float-left"> Announcements </h3>
                    <div class="float-right">
                        <a href="{{ route('admin.announcement.create') }}" class="btn btn-primary ">  <i class="fa fa-plus" aria-hidden="true"></i> Create announcement</a>
                    </div>

                </div>

                <div class="card-body">
                    @if ($message = Session::get('success'))
                            
                    <div class="alert alert-success alert-block">
    
                        <button type="button" class="close" data-dismiss="alert">×</button>
    
                        <strong>{{ $message }}</strong>
    
                    </div>
    
                    @endif
                       <div class="row ">
                        
                            @foreach ($announcements as $announcement)
                            <div class="col-sm-4">
                              <div class="card shadow hover">
                                  
                                  <div class="card-body">
                                     
                                    <h5 class="card-title font-weight-bolder small">{{ $announcement->tittle }}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted text-info" style="font-size:10px;">Created On <br> {{ $announcement->created_at }}</h6> <hr>
                                    <p class="card-text">{{ str_limit($announcement->message, '41') }}</p> <hr>
                                      <a href="{{route('admin.announcement.edit',$announcement->id)}}" class="card-link">
                                        <button type="button" class="btn btn-default text-dark float-left mr-1" style="padding:5px;"> 
                                          <i class="fas fa-edit "></i> Edit
                                        </button>
                                      </a>
                                    <a href="#" class="card-link"> 
                                      <form action="{{route('admin.announcement.destroy',$announcement)}}" method="post" class="float-left">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-default text-danger" style="padding:5px;"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                                    </form>
                                  </a>
                                 

  
                                  <a href="{{route('admin.notification.show',$announcement->id)}}" class="card-link float-right">
                                      <button type="button" class="btn btn-primary float-left mr-1" style="padding:5px;"> 
                                        <i class="fas fa-bullhorn "></i>  Broadcast 
                                      </button>
                                    </a>
                                  </div>
                                </div>
                              </div>
                          @endforeach
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


@endsection